// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashNoticeController from "./flash_notice_controller"
application.register("flash-notice", FlashNoticeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MemoAiPanelController from "./memo_ai_panel_controller"
application.register("memo-ai-panel", MemoAiPanelController)

import MemoAiSidebarController from "./memo_ai_sidebar_controller"
application.register("memo-ai-sidebar", MemoAiSidebarController)

import MemoAttachmentsController from "./memo_attachments_controller"
application.register("memo-attachments", MemoAttachmentsController)

import MemoBodyEditorController from "./memo_body_editor_controller"
application.register("memo-body-editor", MemoBodyEditorController)

import MemoChecklistController from "./memo_checklist_controller"
application.register("memo-checklist", MemoChecklistController)

import MemoShowMetadataController from "./memo_show_metadata_controller"
application.register("memo-show-metadata", MemoShowMetadataController)

import BoardAddMemoController from "./board_add_memo_controller"
application.register("board-add-memo", BoardAddMemoController)

import BoardKanbanDndController from "./board_kanban_dnd_controller"
application.register("board-kanban-dnd", BoardKanbanDndController)

import DiagramSourceViewerController from "./diagram_source_viewer_controller"
application.register("diagram-source-viewer", DiagramSourceViewerController)

import DiagramSvgViewerController from "./diagram_svg_viewer_controller"
application.register("diagram-svg-viewer", DiagramSvgViewerController)

import MemoDiagramEditorController from "./memo_diagram_editor_controller"
application.register("memo-diagram-editor", MemoDiagramEditorController)

import ExpandableHintController from "./expandable_hint_controller"
application.register("expandable-hint", ExpandableHintController)

import MemoDirectoryNavOpenController from "./memo_directory_nav_open_controller"
application.register("memo-directory-nav-open", MemoDirectoryNavOpenController)

import MemoDirectoryDialogController from "./memo_directory_dialog_controller"
application.register("memo-directory-dialog", MemoDirectoryDialogController)

import MemoDirectoryDndController from "./memo_directory_dnd_controller"
application.register("memo-directory-dnd", MemoDirectoryDndController)

import MemoDirectoryParentPickerController from "./memo_directory_parent_picker_controller"
application.register("memo-directory-parent-picker", MemoDirectoryParentPickerController)

import MemoDirectorySidebarOpenController from "./memo_directory_sidebar_open_controller"
application.register("memo-directory-sidebar-open", MemoDirectorySidebarOpenController)

import MemoWikiCreateController from "./memo_wiki_create_controller"
application.register("memo-wiki-create", MemoWikiCreateController)

import MemoDraftController from "./memo_draft_controller"
application.register("memo-draft", MemoDraftController)

if (import.meta.hot) {
  import.meta.hot.accept("./memo_draft_controller", (mod) => {
    application.unload("memo-draft")
    application.register("memo-draft", mod.default)
  })
}

import MemoSearchController from "./memo_search_controller"
application.register("memo-search", MemoSearchController)

import MemoSidebarController from "./memo_sidebar_controller"
application.register("memo-sidebar", MemoSidebarController)

import NotebookMemoTreeController from "./notebook_memo_tree_controller"
application.register("notebook-memo-tree", NotebookMemoTreeController)

import UserMenuController from "./user_menu_controller"
application.register("user-menu", UserMenuController)

import ThemeStudioController from "./theme_studio_controller"
application.register("theme-studio", ThemeStudioController)
