// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MemoDirectoryDndController from "./memo_directory_dnd_controller"
application.register("memo-directory-dnd", MemoDirectoryDndController)

import MemoDirectoryParentPickerController from "./memo_directory_parent_picker_controller"
application.register("memo-directory-parent-picker", MemoDirectoryParentPickerController)

import MemoDraftController from "./memo_draft_controller"
application.register("memo-draft", MemoDraftController)

import MemoSearchController from "./memo_search_controller"
application.register("memo-search", MemoSearchController)

import MemoSidebarController from "./memo_sidebar_controller"
application.register("memo-sidebar", MemoSidebarController)

import UserMenuController from "./user_menu_controller"
application.register("user-menu", UserMenuController)
