/** Preset palettes from asciidoctor-skins (gh-pages/css/*.css :root blocks). */

/** @typedef {{ id: string, label: string, source: string, yaml: Record<string, string> }} AsciiDoctorSkinPreset */

/** @type {AsciiDoctorSkinPreset[]} */
export const ASCIIDOCTOR_SKIN_PRESETS = [
  {
    id: "material-grey",
    label: "Material Grey",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#9E9E9E",
      secondarycolor: "#ba3925",
      tertiarycolor: "#186d7a",
      sidebarbackground: "#212121",
      linkcolor: "#EEEEEE",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "dark",
    label: "Dark",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#282c34",
      primarycolor: "#f39c12",
      secondarycolor: "#03a9f4",
      tertiarycolor: "#4db6ac",
      sidebarbackground: "#21252b",
      linkcolor: "#f44336",
      linkcoloralternate: "#ff9800",
      white: "#FFFFFF",
    },
  },
  {
    id: "clean",
    label: "Clean",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#2c3e50",
      secondarycolor: "#ba3925",
      tertiarycolor: "#186d7a",
      sidebarbackground: "#CCC",
      linkcolor: "#b71c1c",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "tufte",
    label: "Tufte",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#fffff8",
      primarycolor: "#111111",
      secondarycolor: "#111111",
      tertiarycolor: "#111111",
      sidebarbackground: "#eeeeee",
      linkcolor: "#111111",
      linkcoloralternate: "#111111",
      white: "#fffff8",
      black: "#111111",
    },
  },
  {
    id: "material-blue",
    label: "Material Blue",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#2196F3",
      secondarycolor: "#ba3925",
      tertiarycolor: "#186d7a",
      sidebarbackground: "#0D47A1",
      linkcolor: "#1976D2",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "material-green",
    label: "Material Green",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#4CAF50",
      secondarycolor: "#ba3925",
      tertiarycolor: "#186d7a",
      sidebarbackground: "#1B5E20",
      linkcolor: "#2E7D32",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "material-teal",
    label: "Material Teal",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#009688",
      secondarycolor: "#ba3925",
      tertiarycolor: "#186d7a",
      sidebarbackground: "#004d40",
      linkcolor: "#00796B",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "material-red",
    label: "Material Red",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#F44336",
      secondarycolor: "#ba3925",
      tertiarycolor: "#186d7a",
      sidebarbackground: "#B71C1C",
      linkcolor: "#C62828",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "material-purple",
    label: "Material Purple",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#9C27B0",
      secondarycolor: "#ba3925",
      tertiarycolor: "#186d7a",
      sidebarbackground: "#4A148C",
      linkcolor: "#6A1B9A",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "material-orange",
    label: "Material Orange",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#FF9800",
      secondarycolor: "#ba3925",
      tertiarycolor: "#186d7a",
      sidebarbackground: "#E65100",
      linkcolor: "#EF6C00",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "material-brown",
    label: "Material Brown",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#795548",
      secondarycolor: "#ba3925",
      tertiarycolor: "#186d7a",
      sidebarbackground: "#3E2723",
      linkcolor: "#5D4037",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "fedora",
    label: "Fedora",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#294172",
      secondarycolor: "#3c6eb4",
      tertiarycolor: "#cccccc",
      sidebarbackground: "#CACACA",
      linkcolor: "#0D47A1",
      linkcoloralternate: "#db3279",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "gazette",
    label: "Gazette",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#000000",
      secondarycolor: "#aaaaaa",
      tertiarycolor: "#cccccc",
      sidebarbackground: "#FFFFFF",
      linkcolor: "#0D47A1",
      linkcoloralternate: "#B71C1C",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "notebook",
    label: "Notebook",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#000000",
      secondarycolor: "#1a237e",
      tertiarycolor: "#cccccc",
      sidebarbackground: "#CACACA",
      linkcolor: "#0D47A1",
      linkcoloralternate: "#B71C1C",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "ubuntu",
    label: "Ubuntu",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#E95420",
      secondarycolor: "#333333",
      tertiarycolor: "#772953",
      sidebarbackground: "#cccccc",
      linkcolor: "#b71c1c",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "italian-pop",
    label: "Italian Pop",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#b71c1c",
      secondarycolor: "#1b5e20",
      tertiarycolor: "#186d7a",
      sidebarbackground: "#cccccc",
      linkcolor: "#b71c1c",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
  {
    id: "monospace",
    label: "Monospace",
    source: "asciidoctor-skins",
    yaml: {
      maincolor: "#FFFFFF",
      primarycolor: "#000000",
      secondarycolor: "#000000",
      tertiarycolor: "#000000",
      sidebarbackground: "#cccccc",
      linkcolor: "#000000",
      linkcoloralternate: "#f44336",
      white: "#FFFFFF",
      black: "#000000",
    },
  },
]

/** @param {string} presetId */
export function findAsciiDoctorSkinPreset(presetId) {
  return ASCIIDOCTOR_SKIN_PRESETS.find((preset) => preset.id === presetId) ?? null
}
